name: Tests

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Setup mongodb
        uses: supercharge/mongodb-github-action@1.2.0
        with:
          mongodb-version: '4.2'


      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify

  check-quality:
    runs-on: ubuntu-latest
    name: A job to check my code quality
    steps:
      - name: Check code meets quality standards
        id: code-inspector
        uses: codeinspectorio/github-action@master
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          code_inspector_api_token: ${{ secrets.MANAGER }}
          force_ref: 'none'
          min_quality_grade: 'WARNING'
          min_quality_score: '50'
          max_defects_rate: '0.0001'
          max_complex_functions_rate: '0.0001'
          max_long_functions_rate: '0.0001'
          project_name: ''
          max_timeout_sec: '600'